// Configuration for YTPlayer
// Automatically Generated by PhantomBot at Startup
// Do NOT Modify! Overwritten when PhantomBot is restarted!
var playerPort = 25003;
var channelName = "lapotor";
var auth="VtDt3br4y4BjHF8kOpmoc3W2d4s7za";
var http="http://";
function getPlayerPort() { return playerPort; }
function getChannelName() { return channelName; }
function getAuth() { return auth; }
function getProtocol() { return http; }
