// Configuration for YTPlayer
// Automatically Generated by PhantomBot at Startup
// Do NOT Modify! Overwritten when PhantomBot is restarted!
var playerPort = 29003;
var channelName = "vesturotv";
var auth="l6TqklW6EkMgk3jybrtUnuuze98t16";
var http="http://";
function getPlayerPort() { return playerPort; }
function getChannelName() { return channelName; }
function getAuth() { return auth; }
function getProtocol() { return http; }
